PLATFORM ?= rpi2
ARCHFLAGS = -DBOOTLOADER
SRCDIR = ./FFsh/src ./FFsh/ff15/source
EXCLUDESRC = ./FFsh/ff15/source/diskio.c ./FFsh/ff15/source/ffsystem.c
RULESHOME ?= ../../Rules
INCLUDEPATH += FFsh/ff15/source
PROJKIND = lib
include ../../bootloader/raspi.mk